# Generated by Django 2.2.6 on 2019-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191023_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('DRF', 'DRF'), ('GraphQL', 'GraphQL'), ('OOP', 'OOP'), ('Others', 'Others')], default='Python', max_length=10),
        ),
    ]
