# Generated by Django 2.2.6 on 2019-10-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
